### ISSUE TITLE
Residuals: Fix language in manual at least

### ISSUE THREAD

**Issue by stephlj** [stephlj/Traces#16]
Need to be more careful about how I talk about residuals. From Matt:
When comparing fits (polynomial vs affine) compare residuals on held out data otherwise polynomial (more params) always does better

**Comment by stephlj** [comment]
Could you take a look at point (9) on pgs 14-15 of the manual, and the caption to figure 7?

**Comment by mattjj** [comment]
LGTM! (Though you could delete some "Note that" phrases at the starts of sentences without changing their meaning.)

**Comment by stephlj** [comment]
hey I like my note that's :) Thanks!
